## ver_test_5.script -- a test case for gold

## Copyright (C) 2008-2023 Free Software Foundation, Inc.
## Written by Ian Lance Taylor <iant@google.com>

## This file is part of gold.

## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.

## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.

## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston,
## MA 02110-1301, USA.

# This tests that we don't break when assigning a version to an
# undefined symbol.  This is used with ver_test_2.cc, which defines
# t3_2 but only refers to t2_2.

VER5 {
  global:
    t2_2;
    t3_2;
};
