FRAMEWORK=Cocoa
SRCS=Cocoa.m
INCS=Cocoa.h

RESOURCES=Info.plist
CFLAGS+= ${FMWK_CFLAGS} -I.. -I../Foundation/Headers -I../AppKit/Headers -I../OpenGL/include -I../libobjc2

.include <airyx.framework.mk>
