=head1 NAME

htmllink - Test HTML links

=head1 LINKS

L</"section1">

L</"section 2">

L</"section three">

L</"item1">

L</"item 2">

L</"item three">

L</section1>

L</section 2>

L</section three>

L</item1>

L</item 2>

L</item three>

L<"section1">

L<"section 2">

L<"section three">

L<"item1">

L<"item 2">

L<"item three">

L<text|/"section1">

L<text|/"section 2">

L<text|/"section three">

L<text|/"item1">

L<text|/"item 2">

L<text|/"item three">

L<text|/section1>

L<text|/section 2>

L<text|/section three>

L<text|/item1>

L<text|/item 2>

L<text|/item three>

L<text|"section1">

L<text|"section 2">

L<text|"section three">

L<text|"item1">

L<text|"item 2">

L<text|"item three">

=head1 TARGETS

=head2 section1

This is section one.

=head2 section 2

This is section two.

=head2 section three

This is section three.

=over 4

=item item1 X<item> X<one>

This is item one.

=item item 2
X<item> X<two>

This is item two.

=item item three X<item>
X<three>

This is item three.

=back
