.TH tapi 1 2023-03-08 Darwin "TAPI Tool Documentation"
.SH NAME
tapi \- Text-based Stubs Tool
.SH SYNOPSIS
\fItapi\fR [\-\-version] [\-\-help]

\fItapi\fR <command> [<args>]

.SH DESCRIPTION
TAPI can generate text-based stub files (.tbd) from existing Mach\-O libraries
or parse the headers of a framework and infer the text-based stub file from it.

.SH OPTIONS
.PP
\-\-version
.RS 4
Prints the tapi version.
.RE
.PP
\-\-help
.RS 4
Prints the synopsis and a list of the available commands. Use tapi <command>
\-\-help to obtain more information about a particular command.
.RE

.SH TAPI COMMANDS
\fBtapi\-archive\fR(1)
.RS 4
Merge or thin text-based stub files.
.RE
.PP
\fBtapi\-stubify\fR(1)
.RS 4
Create a text-based stub file from a library.
.RE
.PP
\fBtapi\-installapi\fR(1)
.RS 4
Create a text-based stub file by scanning the header files.
.RE
.PP
\fBtapi\-reexport\fR(1)
.RS 4
Create a linker reexport file by scanning the header files.
.RE
.PP
\fBtapi\-tbd\fR(1)
.RS 4
See text-based dynamic library stub (.tbd) format reference.
.RE
.PP

.SH SEE ALSO
tapi\-archive(1), tapi\-stubify(1), tapi\-installapi(1), tapi\-reexport(1), tapi\-tbd(1), ld(1), Mach\-O(5)
