.*: Assembler messages:
.*: Error: condition required -- `cset r4,r2,ne'
.*: Error: r13 not allowed here -- `csetm sp,ne'
.*: Error: r15 not allowed here -- `cinc r3,pc,lt'
.*: Error: r15 not allowed here -- `cinv pc,r2,lt'
.*: Error: r13 not allowed here -- `cneg r3,sp,lt'
.*: Error: instruction not allowed in IT block -- `csinc r3,r2,r4,lt'
.*: Error: instruction cannot be conditional -- `csnegne r3,r2,r4,lt'
