[^:]*: Assembler messages:
[^:]*:2: Error: bad type in SIMD instruction -- `vqdmlah.u8 q1,q2,r0'
[^:]*:3: Error: bad type in SIMD instruction -- `vqrdmlah.u8 q3,q4,r5'
[^:]*:2: Error: bad type in SIMD instruction -- `vqdmlah.u16 q1,q2,r0'
[^:]*:3: Error: bad type in SIMD instruction -- `vqrdmlah.u16 q3,q4,r5'
[^:]*:2: Error: bad type in SIMD instruction -- `vqdmlah.u32 q1,q2,r0'
[^:]*:3: Error: bad type in SIMD instruction -- `vqrdmlah.u32 q3,q4,r5'
