[^:]*: Assembler messages:
[^:]*:2: Error: bad type in SIMD instruction -- `vqdmlash.u8 q0,q2,r0'
[^:]*:3: Error: bad type in SIMD instruction -- `vqrdmlash.u8 q1,q3,r1'
[^:]*:2: Error: bad type in SIMD instruction -- `vqdmlash.u16 q0,q2,r0'
[^:]*:3: Error: bad type in SIMD instruction -- `vqrdmlash.u16 q1,q3,r1'
[^:]*:2: Error: bad type in SIMD instruction -- `vqdmlash.u32 q0,q2,r0'
[^:]*:3: Error: bad type in SIMD instruction -- `vqrdmlash.u32 q1,q3,r1'
