[^:]*: Assembler messages:
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:9: Warning: instruction is UNPREDICTABLE in an IT block
[^:]*:15: Error: bad type in SIMD instruction -- `vcvta.s64.f64 q0,q1'
[^:]*:16: Error: bad type in SIMD instruction -- `vcvta.u64.f64 q0,q1'
[^:]*:17: Error: bad type in SIMD instruction -- `vcvta.f64.s64 q0,q1'
[^:]*:18: Error: bad type in SIMD instruction -- `vcvta.f64.u64 q0,q1'
[^:]*:19: Error: bad type in SIMD instruction -- `vcvtn.s64.f64 q0,q1'
[^:]*:20: Error: bad type in SIMD instruction -- `vcvtn.u64.f64 q0,q1'
[^:]*:21: Error: bad type in SIMD instruction -- `vcvtn.f64.s64 q0,q1'
[^:]*:22: Error: bad type in SIMD instruction -- `vcvtn.f64.u64 q0,q1'
[^:]*:23: Error: bad type in SIMD instruction -- `vcvtp.s64.f64 q0,q1'
[^:]*:24: Error: bad type in SIMD instruction -- `vcvtp.u64.f64 q0,q1'
[^:]*:25: Error: bad type in SIMD instruction -- `vcvtp.f64.s64 q0,q1'
[^:]*:26: Error: bad type in SIMD instruction -- `vcvtp.f64.u64 q0,q1'
[^:]*:27: Error: bad type in SIMD instruction -- `vcvtm.s64.f64 q0,q1'
[^:]*:28: Error: bad type in SIMD instruction -- `vcvtm.u64.f64 q0,q1'
[^:]*:29: Error: bad type in SIMD instruction -- `vcvtm.f64.s64 q0,q1'
[^:]*:30: Error: bad type in SIMD instruction -- `vcvtm.f64.u64 q0,q1'
[^:]*:32: Error: syntax error -- `vcvtaeq.s32.f32 q0,q1'
[^:]*:33: Error: syntax error -- `vcvtaeq.s32.f32 q0,q1'
[^:]*:35: Error: syntax error -- `vcvtaeq.s32.f32 q0,q1'
[^:]*:36: Error: vector predicated instruction should be in VPT/VPST block -- `vcvtat.s32.f32 q0,q1'
[^:]*:38: Error: instruction missing MVE vector predication code -- `vcvta.s32.f32 q0,q1'
[^:]*:40: Error: syntax error -- `vcvtneq.s32.f32 q0,q1'
[^:]*:41: Error: syntax error -- `vcvtneq.s32.f32 q0,q1'
[^:]*:43: Error: syntax error -- `vcvtneq.s32.f32 q0,q1'
[^:]*:44: Error: vector predicated instruction should be in VPT/VPST block -- `vcvtnt.s32.f32 q0,q1'
[^:]*:46: Error: instruction missing MVE vector predication code -- `vcvtn.s32.f32 q0,q1'
[^:]*:48: Error: syntax error -- `vcvtpeq.s32.f32 q0,q1'
[^:]*:49: Error: syntax error -- `vcvtpeq.s32.f32 q0,q1'
[^:]*:51: Error: syntax error -- `vcvtpeq.s32.f32 q0,q1'
[^:]*:52: Error: vector predicated instruction should be in VPT/VPST block -- `vcvtpt.s32.f32 q0,q1'
[^:]*:54: Error: instruction missing MVE vector predication code -- `vcvtp.s32.f32 q0,q1'
[^:]*:56: Error: syntax error -- `vcvtmeq.s32.f32 q0,q1'
[^:]*:57: Error: syntax error -- `vcvtmeq.s32.f32 q0,q1'
[^:]*:59: Error: syntax error -- `vcvtmeq.s32.f32 q0,q1'
[^:]*:60: Error: vector predicated instruction should be in VPT/VPST block -- `vcvtmt.s32.f32 q0,q1'
[^:]*:62: Error: instruction missing MVE vector predication code -- `vcvtm.s32.f32 q0,q1'
