.*shift-bad-pc.s: Assembler messages:
.*shift-bad-pc.s:5: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:6: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:7: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:8: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:5: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:6: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:7: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:8: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:5: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:6: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:7: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:8: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:5: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:6: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:7: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:8: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:5: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:6: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:7: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:8: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:5: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:6: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:7: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:8: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:5: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:6: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:7: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:8: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:5: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:6: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:7: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:8: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:5: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:6: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:7: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:8: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:5: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:6: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:7: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:8: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:20: *Info: macro .*
.*shift-bad-pc.s:14: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:15: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:16: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:14: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:15: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:16: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:14: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:15: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:16: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:14: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:15: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:16: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:14: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:15: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
.*shift-bad-pc.s:16: Warning: using r15 results in unpredictable behaviour
.*shift-bad-pc.s:21: *Info: macro .*
