=encoding utf8

=head1 NAME

perlbot - Links to information on object-oriented programming in Perl

=head1 DESCRIPTION

For information on OO programming with Perl, please see L<perlootut>
and L<perlobj>.

(The above documents supersede the collection of tricks that was formerly here
in perlbot.)

=cut
