# ------------------------------------------------------------------------
#  RAVYNOS BUILD SYSTEM - Frameworks
# ------------------------------------------------------------------------

SUBDIR = CoreFoundation
#SUBDIR += CFNetwork
SUBDIR += Foundation
SUBDIR += CoreServices
SUBDIR += Onyx2D
SUBDIR += CoreGraphics
SUBDIR += OpenGL
SUBDIR += CoreText
SUBDIR += AppKit

all: ${SUBDIR}

Foundation: CoreFoundation

.include <bsd.subdir.mk>
