.include <bsd.prog.mk>

.MAKEFLAGS=
#CONFIGURE_ARGS+=
GMAKE_ARGS+=    INSTALL=${DESTDIR}/legacy/bin/install

all: gnu_configure .WAIT gnu_build
build: gnu_build
clean: gnu_clean
install: gnu_install


