#!/bin/sh

BOOTMODE=$(sysctl -n machdep.bootmethod)
export BOOTMODE

if [ "${BOOTMODE}" = "BIOS" ]; then
  cp /usr/home/liveuser/xorg.conf.d/driver-vesa.conf /etc/X11/xorg.conf >/dev/null 2>/dev/null
fi

if [ "${BOOTMODE}" = "UEFI" ]; then
  cp /usr/home/liveuser/xorg.conf.d/driver-scfb.conf /etc/X11/xorg.conf >/dev/null 2>/dev/null
fi

VMGUEST=$(sysctl -n kern.vm_guest)
export VMGUEST

if [ "${VMGUEST}" = "xen" ]; then
  /usr/sbin/sysrc devd_enable="NO" >/dev/null 2>/dev/null
fi

if [ "${VMGUEST}" = "vmware" ]; then
  rm /etc/X11/xorg.conf >/dev/null 2>/dev/null
  cp /usr/home/liveuser/xorg.conf.d/driver-vmware.conf /etc/X11/xorg.conf >/dev/null 2>/dev/null
  /usr/sbin/sysrc -f /etc/rc.conf vmware_guest_vmblock_enable="YES" >/dev/null 2>/dev/null
  /usr/sbin/sysrc -f /etc/rc.conf vmware_guest_vmmemctl_enable="YES" >/dev/null 2>/dev/null
  /usr/sbin/sysrc -f /etc/rc.conf vmware_guestd_enable="YES" >/dev/null 2>/dev/null
  /usr/sbin/sysrc -f /etc/rc.conf moused_enable="YES" >/dev/null 2>/dev/null
fi

if [ -f "/usr/sbin/pciconf" ] ; then
  /usr/sbin/pciconf -lv 2>/dev/null | /usr/bin/grep -q VirtualBox 2>/dev/null
  if [ $? -eq 0 ] ; then
    rm /etc/X11/xorg.conf >/dev/null 2>/dev/null
    cp /usr/home/liveuser/xorg.conf.d/driver-virtualbox.conf /etc/X11/xorg.conf >/dev/null 2>/dev/null
    /usr/sbin/sysrc -f /etc/rc.conf vboxguest_enable="YES" >/dev/null 2>/dev/null
    /usr/sbin/sysrc -f /etc/rc.conf vboxservice_enable="YES" >/dev/null 2>/dev/null
  else
    /usr/sbin/pkg delete -fy virtualbox-ose-additions >/dev/null 2>/dev/null
  fi
fi

/usr/sbin/sysrc -f /etc/rc.conf linux_enable="YES" >/dev/null 2>/dev/null
/usr/sbin/sysrc -f /etc/rc.conf dbus_enable="YES" >/dev/null 2>/dev/null
/usr/sbin/sysrc -f /etc/rc.conf dsbdriverd_enable="YES" >/dev/null 2>/dev/null
/usr/sbin/sysrc -f /etc/rc.conf kld_list+="sysctlinfo cuse" >/dev/null 2>/dev/null
/usr/sbin/sysrc -f /etc/rc.conf allscreens_kbdflags="-b quiet.off"
/usr/sbin/sysrc -f /etc/rc.conf dhcpcd_enable="YES" >/dev/null 2>/dev/null
/usr/sbin/sysrc -f /etc/rc.conf webcamd_enable="YES" >/dev/null 2>/dev/null
