SCRIPT_NAME=aout
TEXT_START_ADDR=0x1020
case ${LD_FLAG} in
    n|N)	TEXT_START_ADDR=0x1000 ;;
esac
OUTPUT_FORMAT="a.out-ns32k-netbsd"
TARGET_PAGE_SIZE=0x1000
ARCH=ns32k
EXECUTABLE_SYMBOLS='__DYNAMIC = 0;'
EXTRA_EM_FILE=netbsd
