SCRIPT_NAME=pdp11
OUTPUT_FORMAT="a.out-pdp11"
TEXT_START_ADDR=0
TARGET_PAGE_SIZE=8192
EXTRA_EM_FILE=pdp11
ARCH=pdp11

case "$LD_FLAG" in
  *textonly) DATA_SEG_ADDR=0 ;;
  *) DATA_SEG_ADDR=$DATA_ALIGNMENT ;;
esac
