ENTRY("<PRIu32>", "u"),
ENTRY("<PRIu64>", "lu", "llu"),
ENTRY("<PRIuMAX>", "lu", "llu"),
ENTRY("<PRIuPTR>", "u", "lu"),
ENTRY("<PRId32>", "d"),
ENTRY("<PRId64>", "ld", "lld"),
ENTRY("<PRIdMAX>", "ld", "lld"),
ENTRY("<PRIdPTR>", "d", "ld"),
ENTRY("<PRIx32>", "x"),
ENTRY("<PRIx64>", "lx", "llx"),
ENTRY("<PRIxMAX>", "lx", "llx"),
ENTRY("<PRIxPTR>", "x", "lx"),
ENTRY("<PRIX32>", "X"),
ENTRY("<PRIX64>", "lX", "llX"),
ENTRY("<PRIXMAX>","lX", "llX"),
ENTRY("<PRIXPTR>", "X", "lX"),
ENTRY("<PRIo32>", "o"),
ENTRY("<PRIo64>", "lo", "llo"),
ENTRY("<PRIoMAX>", "lo", "llo"),
ENTRY("<PRIoPTR>", "o", "lo"),
ENTRY("<PRIi32>", "i"),
ENTRY("<PRIi64>", "li", "lli"),
ENTRY("<PRIiMAX>", "li", "lli"),
ENTRY("<PRIiPTR>", "i", "li"),
