
add_library(libkext STATIC
	 Trie.hpp
	 AdjustForNewSegmentLocation.cpp
	 cross_link.c
	 OSKextVersion.c
	 macho_util.c
	 fat_util.c
	 MachOFileAbstraction.hpp
	 Architectures.hpp
	 kextsplit.h
	 FileAbstraction.hpp
	./FILES/OSKext.c
)

add_library(ioserviceauthorized STATIC
	 ioserviceauthorized.m
	 open.m
)
add_library(IOServiceAuthorizeAgent STATIC
	 application.m
	 authorize.m
	 device.m
	 preferences.m
	 storage.m
	 usb.m
	 IOServiceAuthorizeAgent.m
)

add_library(IOKit STATIC
	 IOHIDEventObjc.m
	 IOHIDServiceObjc.m
	 IOHIDSessionObjc.m
	 IOHIDConnectionObjc.m
	 IOHIDElementObjc.m
	 IOHIDServiceClientObjc.m
	 IOHIDDeviceObjc.m
	 HIDEventBase.m
	 HIDServiceBase.m
	 HIDSessionBase.m
	 HIDConnectionBase.m
	 HIDElementBase.m
	 HIDServiceClientBase.m
	 HIDDeviceBase.m
	 cross_link.c
	 IOCFSerialize.c
	 IOCFUnserialize.tab.c
	 IOKitLib.c
	 FileAbstraction.hpp
	 IOCFURLAccess.c
	 IOHIDAnalytics.c
	 IODataQueueClient.c
	 IOCFPlugIn.c
	 IOTrap.s
	 Architectures.hpp
	 IOPMLib.c
	 IOPMEnergyPrefs.c
	 IOPMAutoWake.c
	 IOPMRepeatingPower.c
	 IOPMUPSPrefs.c
	 powermanagement.defs
	 IOUSBLib.c
	 IONetworkLib.c
	 IOAccelSurfaceControl.c
	 IOGraphicsLib.c
	 IODisplayLib.c
	 IOEventStatusAPI.c
	 AdjustForNewSegmentLocation.cpp
	 IOHIDLib.c
	 KextManager.c
	 kextmanager_mig.defs
	 IOPowerSources.c
	 IOHIDServiceConnectionCache.c
	 IOPowerSourcesPrivate.c
	 IOPMLibPrivate.c
	 IOSystemConfiguration.c
	 IOHIDValue.c
	 IOHIDSessionFilter.c
	 IOHIDElement.c
	 fat_util.c
	 macho_util.c
	 MachOFileAbstraction.hpp
	 IOHIDDevice.c
	 IOHIDServiceKeys.c
	 IOHIDLibPrivate.c
	 IOHIDManager.c
	 IOHIDQueue.c
	 IOHIDTransaction.c
	 IOHIDEvent.c
	 IOHIDEventSystem.c
	 IOHIDConnectionFilter.c
	 IOHIDEventSystemClient.c
	 IOHIDNotification.c
	 IOHIDService.c
	 IOHIDSession.c
	 IOHIDEventQueue.c
	 IOPMPowerNotifications.c
	 OSKextVersion.c
	 misc_util.c
	 printPList_new.c
	 IOHIDEventSystemMIG.defs
	 IOMIGMachPort.c
	./FILES/OSKext.c
	 IOHIDEventSystemClientMIG.defs
	 IOHIDEventSystemPrivate.c
	 kextsplit.h
	 IOHIDServiceFilter.c
	 IOHIDServiceClient.c
	 IOHIDEventSystemConnection.c
	 IOHIDEventServer.c
	 IOPMAssertions.c
	 IOUserEthernetController.c
	 IOHIDUserDevice.c
	 IOHIDPlugins.c
	 IOPlatformSupport.c
	 Trie.hpp
)
