#!/bin/sh

# PROVIDE: livecd 
# REQUIRE: FILESYSTEMS mountcritremote

. /etc/rc.subr

name="livecd"
desc="LiveCD Assistant"
rcvar="livecd_enable"
start_cmd="livecd_start"
stop_cmd=":"

livecd_start()
{
	check_startmsgs && echo -n 'Running LiveCD assistant'
        /sbin/mdconfig -du md0
        /sbin/mdconfig -du md1
	check_startmsgs && echo '.'
}

run_rc_command "$1"
