if(("${CC}" STREQUAL "") AND (NOT ("$ENV{CC}" STREQUAL "")))
    set(HOST_CC $ENV{CC})
elseif("${CC}" STREQUAL "")
    set(HOST_CC /usr/bin/cc)
endif()
if(("${CXX}" STREQUAL "") AND (NOT ("$ENV{CXX}" STREQUAL "")))
    set(HOST_CXX $ENV{CXX})
elseif("${CXX}" STREQUAL "")
    set(HOST_CXX /usr/bin/c++)
endif()

set(CC ${TOOLS}/cc)
set(CXX ${TOOLS}/c++)
set(LD ${TOOLS}/ld64)
set(AR ${TOOLS}/ar)
set(RANLIB ${TOOLS}/ranlib)
set(NM ${TOOLS}/nm)
set(CODESIGN_ALLOCATE ${TOOLS}/codesign_allocate)
set(CTFCONVERT ${TOOLS}/ctfconvert)
set(CTFMERGE ${TOOLS}/ctfmerge)
set(CTFINSERT ${TOOLS}/ctfinsert)
set(IIG /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/iig)
set(MIG ${TOOLS}/mig)
set(MIGCOM ${TOOLCHAIN}/usr/libexec/migcom)
set(STRIP ${TOOLS}/strip)
set(LIPO ${TOOLS}/lipo)
set(NM ${TOOLS}/nm)
set(NMEDIT ${TOOLS}/nmedit)
set(LIBTOOL ${TOOLS}/libtool)
set(UNIFDEF ${TOOLS}/unifdef)
set(DSYMUTIL ${TOOLS}/dsymutil)
set(XCRUN ${TOOLS}/xcrun)
set(XCBUILD ${TOOLS}/xcbuild)
set(XCODEBUILD ${TOOLS}/xcodebuild)
set(GMAKE ${TOOLS}/make)
