.\" Copyright (c) 2019, Apple Computer, Inc.  All rights reserved.
.\"
.Dd September 9, 2019   \" DATE
.Dt objcdt 1           \" Program name and manual section number
.Os "OS X"
.Sh NAME
.Nm objcdt
.Nd Tool to debug objective-C usage in live processes
.Sh SYNOPSIS
.Nm objcdt
.Sh DESCRIPTION
The
.Nm
utility is a small CLI with embedded help that can dump some information about
the Objective-C runtime state in live processes.
.Pp
Help can be obtained using
.Nm
.Ar help
.Ed
