add_subdirectory(IOGraphicsFamily)
add_subdirectory(IONDRVSupport)

#add_library(IOGTrace STATIC
#	 IOGTrace.cpp
#	./tools/Utilities/IOGDiagnoseUtils.cpp
#)

#add_library(IOGDiagnoseDecode STATIC
#	 iogdecoder.cpp
#	 abldecoder.cpp
#	 IOGDiagnoseDecode.cpp
#	 ContinuousTimeFormatter.cpp
#	 agdcdecoder.cpp
#)

#add_executable(iogttest SOURCES
#	 iogttest.cpp
#	 args.cpp
#)

#add_executable(iogctl SOURCES
#	./tools/iogctl.m
#)

#add_executable(iogdiagnose SOURCES
#	./iogdiagnose/iogdiagnose.cpp
#	./tools/Utilities/IOGDiagnoseUtils.cpp
#)
