.*: Assembler messages:
.*:11: Error: .*
.*:23: *Info: macro .*
.*:11: Error: .*
.*:25: *Info: macro .*
.*:11: Error: .*
.*:27: *Info: macro .*
.*:11: Error: .*
.*:31: *Info: macro .*
.*:11: Error: .*
.*:33: *Info: macro .*
.*:11: Error: .*
.*:35: *Info: macro .*
.*:11: Error: .*
.*:39: *Info: macro .*
.*:11: Error: .*
.*:41: *Info: macro .*
.*:4: Error: .*
.*:43: *Info: macro .*
.*:4: Error: .*
.*:44: *Info: macro .*
.*:4: Error: .*
.*:45: *Info: macro .*
.*:4: Error: .*
.*:50: *Info: macro .*
.*:4: Error: .*
.*:51: *Info: macro .*
.*:4: Error: .*
.*:52: *Info: macro .*
.*:4: Error: .*
.*:53: *Info: macro .*
.*:4: Error: .*
.*:55: *Info: macro .*
.*:4: Error: .*
.*:56: *Info: macro .*
.*:4: Error: .*
.*:57: *Info: macro .*
.*:4: Error: .*
.*:58: *Info: macro .*
.*:11: Error: .*
.*:60: *Info: macro .*
.*:4: Error: .*
.*:63: *Info: macro .*
.*:4: Error: .*
.*:64: *Info: macro .*
.*:4: Error: .*
.*:65: *Info: macro .*
.*:4: Error: .*
.*:66: *Info: macro .*
.*:11: Error: .*
.*:68: *Info: macro .*
.*:4: Error: .*
.*:71: *Info: macro .*
.*:4: Error: .*
.*:72: *Info: macro .*
.*:4: Error: .*
.*:73: *Info: macro .*
.*:4: Error: .*
.*:74: *Info: macro .*
.*:4: Error: .*
.*:76: *Info: macro .*
.*:4: Error: .*
.*:77: *Info: macro .*
.*:4: Error: .*
.*:78: *Info: macro .*
.*:4: Error: .*
.*:79: *Info: macro .*
.*:4: Error: .*
.*:80: *Info: macro .*
.*:4: Error: .*
.*:81: *Info: macro .*
.*:4: Error: .*
.*:82: *Info: macro .*
.*:4: Error: .*
.*:83: *Info: macro .*
.*:4: Error: .*
.*:84: *Info: macro .*
.*:4: Error: .*
.*:85: *Info: macro .*
.*:4: Error: .*
.*:86: *Info: macro .*
.*:11: Error: .*
.*:89: *Info: macro .*
.*:11: Error: .*
.*:91: *Info: macro .*
.*:11: Error: .*
.*:93: *Info: macro .*
.*:11: Error: .*
.*:97: *Info: macro .*
.*:11: Error: .*
.*:99: *Info: macro .*
.*:11: Error: .*
.*:101: *Info: macro .*
.*:11: Error: .*
.*:105: *Info: macro .*
.*:11: Error: .*
.*:107: *Info: macro .*
.*:4: Error: .*
.*:109: *Info: macro .*
.*:4: Error: .*
.*:110: *Info: macro .*
.*:4: Error: .*
.*:111: *Info: macro .*
.*:4: Error: .*
.*:116: *Info: macro .*
.*:4: Error: .*
.*:117: *Info: macro .*
.*:4: Error: .*
.*:118: *Info: macro .*
.*:4: Error: .*
.*:119: *Info: macro .*
.*:11: Error: .*
.*:123: *Info: macro .*
.*:11: Error: .*
.*:125: *Info: macro .*
.*:11: Error: .*
.*:127: *Info: macro .*
.*:11: Error: .*
.*:131: *Info: macro .*
.*:11: Error: .*
.*:133: *Info: macro .*
.*:11: Error: .*
.*:135: *Info: macro .*
.*:11: Error: .*
.*:139: *Info: macro .*
.*:11: Error: .*
.*:141: *Info: macro .*
.*:11: Error: .*
.*:143: *Info: macro .*
.*:11: Error: .*
.*:144: *Info: macro .*
.*:11: Error: .*
.*:145: *Info: macro .*
.*:11: Error: .*
.*:150: *Info: macro .*
.*:11: Error: .*
.*:151: *Info: macro .*
.*:11: Error: .*
.*:152: *Info: macro .*
.*:11: Error: .*
.*:153: *Info: macro .*
