.*: Assembler messages:
.*:17: Error: .*
.*:28: *Info: macro .*
.*:17: Error: .*
.*:29: *Info: macro .*
.*:17: Error: .*
.*:36: *Info: macro .*
.*:17: Error: .*
.*:37: *Info: macro .*
.*:4: Error: .*
.*:43: *Info: macro .*
.*:4: Error: .*
.*:44: *Info: macro .*
.*:4: Error: .*
.*:45: *Info: macro .*
.*:17: Error: .*
.*:46: *Info: macro .*
.*:17: Error: .*
.*:47: *Info: macro .*
.*:17: Error: .*
.*:48: *Info: macro .*
.*:17: Error: .*
.*:49: *Info: macro .*
.*:4: Error: .*
.*:50: *Info: macro .*
.*:4: Error: .*
.*:51: *Info: macro .*
.*:4: Error: .*
.*:52: *Info: macro .*
.*:4: Error: .*
.*:53: *Info: macro .*
.*:4: Error: .*
.*:55: *Info: macro .*
.*:4: Error: .*
.*:56: *Info: macro .*
.*:4: Error: .*
.*:57: *Info: macro .*
.*:4: Error: .*
.*:58: *Info: macro .*
.*:17: Error: .*
.*:61: *Info: macro .*
.*:17: Error: .*
.*:62: *Info: macro .*
.*:4: Error: .*
.*:63: *Info: macro .*
.*:4: Error: .*
.*:64: *Info: macro .*
.*:4: Error: .*
.*:65: *Info: macro .*
.*:4: Error: .*
.*:66: *Info: macro .*
.*:17: Error: .*
.*:69: *Info: macro .*
.*:17: Error: .*
.*:70: *Info: macro .*
.*:4: Error: .*
.*:71: *Info: macro .*
.*:4: Error: .*
.*:72: *Info: macro .*
.*:4: Error: .*
.*:73: *Info: macro .*
.*:4: Error: .*
.*:74: *Info: macro .*
.*:4: Error: .*
.*:76: *Info: macro .*
.*:4: Error: .*
.*:77: *Info: macro .*
.*:4: Error: .*
.*:78: *Info: macro .*
.*:4: Error: .*
.*:79: *Info: macro .*
.*:4: Error: .*
.*:80: *Info: macro .*
.*:4: Error: .*
.*:81: *Info: macro .*
.*:4: Error: .*
.*:82: *Info: macro .*
.*:4: Error: .*
.*:83: *Info: macro .*
.*:4: Error: .*
.*:84: *Info: macro .*
.*:4: Error: .*
.*:85: *Info: macro .*
.*:4: Error: .*
.*:86: *Info: macro .*
.*:17: Error: .*
.*:94: *Info: macro .*
.*:17: Error: .*
.*:95: *Info: macro .*
.*:17: Error: .*
.*:102: *Info: macro .*
.*:17: Error: .*
.*:103: *Info: macro .*
.*:4: Error: .*
.*:109: *Info: macro .*
.*:4: Error: .*
.*:110: *Info: macro .*
.*:4: Error: .*
.*:111: *Info: macro .*
.*:17: Error: .*
.*:112: *Info: macro .*
.*:17: Error: .*
.*:113: *Info: macro .*
.*:17: Error: .*
.*:114: *Info: macro .*
.*:17: Error: .*
.*:115: *Info: macro .*
.*:4: Error: .*
.*:116: *Info: macro .*
.*:4: Error: .*
.*:117: *Info: macro .*
.*:4: Error: .*
.*:118: *Info: macro .*
.*:4: Error: .*
.*:119: *Info: macro .*
