
=encoding iso-8859-7

=head1 NAME

Ολυμπιακός Ύμνος -- Κωστής Παλαμάς

=head1 DESCRIPTION

Αρχαίο Πνεύμ' αθάνατον, αγνέ πατέρα
του ωραίου, του μεγάλου και τ' αληθινού,

κατέβα, φανερώσου κι άστραψ' εδώ πέρα
στη δόξα της δικής σου γης και τ' ουρανού.

Στο δρόμο και στο πάλεμα και στο λιθάρι,
στων ευγενών Αγώνων λάμψε την ορμή,

και με τ' αμάραντο στεφάνωσε κλωνάρι
και σιδερένιο πλάσε κι άξιο το κορμί.

Κάμποι, βουνά και πέλαγα φέγγουν μαζί σου
σαν ένας λευκοπόρφυρος μέγας ναός,

και τρέχει στο ναό εδώ προσκυνητής σου.
Αρχαίο Πνεύμ' αθάνατο, κάθε λαός.

=cut


The above is the Olympic Hymn, by Kostis Palamas.
Yup, it's in Greek.

