.include <internal/framework.common.mk>

FRAMEWORK=CoreVideo
SRCS= CVDisplayLink.m
INCS= CVBase.h CVDisplayLink.h CVReturn.h CoreVideo.h
RESOURCES=Info.plist 
CFLAGS+= ${FMWK_CFLAGS} -I../OpenGL/include -I.. -I../libobjc2 -I../Foundation/Headers

.include <airyx.framework.mk>
