.*: Assembler messages:
.*:3: Warning: .*shortened.*
.*:14:  Info: .*
.*:3: Warning: .*shortened.*
.*:18:  Info: .*
.*:3: Warning: .*shortened.*
.*:22:  Info: .*
.*:3: Warning: .*shortened.*
.*:31:  Info: .*
.*:3: Warning: .*shortened.*
.*:79:  Info: .*
.*:3: Warning: .*shortened.*
.*:95:  Info: .*
.*:3: Warning: .*shortened.*
.*:124:  Info: .*
.*:3: Warning: .*shortened.*
.*:148:  Info: .*
.*:3: Warning: .*shortened.*
.*:151:  Info: .*
.*:3: Warning: .*shortened.*
.*:161:  Info: .*
