.*: Assembler messages:
.*:3: Warning: .*shortened.*
.*:30:  Info: .*
.*:3: Warning: .*shortened.*
.*:34:  Info: .*
.*:3: Warning: .*shortened.*
.*:38:  Info: .*
.*:3: Warning: .*shortened.*
.*:47:  Info: .*
.*:3: Warning: .*shortened.*
.*:99:  Info: .*
.*:3: Warning: .*shortened.*
.*:117:  Info: .*
.*:3: Warning: .*shortened.*
.*:146:  Info: .*
.*:3: Warning: .*shortened.*
.*:170:  Info: .*
.*:3: Warning: .*shortened.*
.*:175:  Info: .*
.*:3: Warning: .*shortened.*
.*:179:  Info: .*
