.*: Assembler messages:
.*:7: Warning: .*
.*:7: Warning: .*
.*:10: Warning: .*
.*:13: Warning: .*
.*:18: Warning: .*
.*:19: Warning: .*
.*:22: Warning: .*
.*:25: Warning: .*
.*:28: Warning: .*

.*:54: Warning: .*
.*:54: Warning: .*
.*:57: Warning: .*
.*:60: Warning: .*
.*:66: Warning: .*
.*:67: Warning: .*
.*:70: Warning: .*
.*:73: Warning: .*
.*:76: Warning: .*
