.*: Assembler messages:
.*:6: Warning: .*
.*:7: Warning: .*
.*:8: Warning: .*
.*:12: Warning: .*
.*:14: Warning: .*
.*:16: Warning: .*
.*:18: Warning: .*
.*:20: Warning: .*
.*:22: Warning: .*
.*:24: Warning: .*
.*:26: Warning: .*
.*:28: Warning: .*
