.* Assembler messages:
.*:5: Error: all tmm registers must be distinct for `tdpfp16ps'
.*:6: Error: all tmm registers must be distinct for `tdpfp16ps'
.*:7: Error: all tmm registers must be distinct for `tdpfp16ps'
.*:10: Error: all tmm registers must be distinct for `tdpfp16ps'
.*:11: Error: all tmm registers must be distinct for `tdpfp16ps'
.*:12: Error: all tmm registers must be distinct for `tdpfp16ps'
