.* Assembler messages:
.*:5: Error: invalid instruction suffix for `lkgs'
.*:6: Error: invalid instruction suffix for `lkgs'
.*:7: Error: invalid instruction suffix for `lkgs'
.*:8: Error: invalid instruction suffix for `lkgs'
.*:11: Error: invalid instruction suffix for `lkgs'
.*:12: Error: invalid instruction suffix for `lkgs'
.*:13: Error: invalid instruction suffix for `lkgs'
.*:14: Error: invalid instruction suffix for `lkgs'
