.TH GETSEGBYNAME 3  "October 3, 2008" "Apple, Inc."
.SH NAME
getsegbyname \- get the segment command for the named segment
.SH SYNOPSIS
.nf
\fB#include <mach-o/getsect.h>\fR
.PP
const struct segment_command *\fBgetsegbyname\fR(const char *\fIsegname\fR);
.fi
.SH DESCRIPTION
This routine returns the segment_command structure for the named segment if it
exists in the Mach-O (Mach object) executable
.IR getsegbyname (3)
is linked into.  Otherwise
.IR getsegbyname (3)
returns
.SM NULL.
It uses the link editor defined symbol _mh_execute_header and
just looks through the load commands.  Since these are mapped into the
.SM \_\|\_TEXT
segment they are read-only and thus
.I const
by default.
If this is to be used in executables linked with
.B \-pie
then the value return by the call to
.IR _dyld_get_image_vmaddr_slide (0)
will need to be added to the
.B vmaddr
field of the segment_command struct.
.SH "SEE ALSO"
end(3), getsectbyname(3)
