/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: ../src/gperf -j1 -i 1 -g -o -t -N is_reserved_word -k'1,3,$'  */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif


/* Command-line: gperf -j1 -i 1 -g -o -t -N is_reserved_word -k1,3,$ objc.gperf  */ 
struct resword { char *name; short token; enum rid rid; };

#define TOTAL_KEYWORDS 59
#define MIN_WORD_LENGTH 2
#define MAX_WORD_LENGTH 15
#define MIN_HASH_VALUE 8
#define MAX_HASH_VALUE 95
/* maximum key range = 88, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash (register const char *str, register size_t len)
{
  static unsigned char asso_values[] =
    {
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 19, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96,  2, 96,  2,  1, 10,
      26,  1, 23, 27, 27, 24, 96,  1, 25, 36,
      10, 34, 23, 96, 10,  6,  8, 11, 41,  2,
      96, 96, 23, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96, 96, 96, 96, 96,
      96, 96, 96, 96, 96, 96
    };
  register unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[2]];
      /*FALLTHROUGH*/
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

struct resword *
is_reserved_word (register const char *str, register size_t len)
{
  static struct resword wordlist[] =
    {
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {"break", BREAK, NORID},
      {""}, {""}, {""},
      {"else", ELSE, NORID},
      {"__asm__", ASM, NORID},
      {""}, {""},
      {"__attribute", ATTRIBUTE, NORID},
      {"__alignof__", ALIGNOF, NORID},
      {"__extension__", EXTENSION, NORID},
      {"__attribute__", ATTRIBUTE, NORID},
      {"__signed__", TYPESPEC, RID_SIGNED},
      {"case", CASE, NORID},
      {"__typeof__", TYPEOF, NORID},
      {"__const__", TYPE_QUAL, RID_CONST},
      {"static", SCSPEC, RID_STATIC},
      {"extern", SCSPEC, RID_EXTERN},
      {"char", TYPESPEC, RID_CHAR},
      {"__const", TYPE_QUAL, RID_CONST},
      {""},
      {"continue", CONTINUE, NORID},
      {"struct", STRUCT, NORID},
      {"@defs", DEFS, NORID},
      {"while", WHILE, NORID},
      {"const", TYPE_QUAL, RID_CONST},
      {"return", RETURN, NORID},
      {"__inline", SCSPEC, RID_INLINE},
      {"__alignof", ALIGNOF, NORID},
      {"@encode", ENCODE, NORID},
      {"__inline__", SCSPEC, RID_INLINE},
      {"@selector", SELECTOR, NORID},
      {"@interface", INTERFACE, NORID},
      {"__typeof", TYPEOF, NORID},
      {"__signed", TYPESPEC, RID_SIGNED},
      {"int", TYPESPEC, RID_INT},
      {"double", TYPESPEC, RID_DOUBLE},
      {"__asm", ASM, NORID},
      {"for", FOR, NORID},
      {"@public", PUBLIC, NORID},
      {"auto", SCSPEC, RID_AUTO},
      {"if", IF, NORID},
      {"union", UNION, NORID},
      {"unsigned", TYPESPEC, RID_UNSIGNED},
      {"enum", ENUM, NORID},
      {"short", TYPESPEC, RID_SHORT},
      {"__volatile", TYPE_QUAL, RID_VOLATILE},
      {"register", SCSPEC, RID_REGISTER},
      {"inline", SCSPEC, RID_INLINE},
      {"__volatile__", TYPE_QUAL, RID_VOLATILE},
      {"sizeof", SIZEOF, NORID},
      {"@end", END, NORID},
      {"typeof", TYPEOF, NORID},
      {"typedef", SCSPEC, RID_TYPEDEF},
      {"do", DO, NORID},
      {"switch", SWITCH, NORID},
      {"default", DEFAULT, NORID},
      {"signed", TYPESPEC, RID_SIGNED},
      {"long", TYPESPEC, RID_LONG},
      {""}, {""}, {""},
      {"float", TYPESPEC, RID_FLOAT},
      {""}, {""},
      {"goto", GOTO, NORID},
      {""},
      {"volatile", TYPE_QUAL, RID_VOLATILE},
      {""},
      {"asm", ASM, NORID},
      {""}, {""},
      {"@implementation", IMPLEMENTATION, NORID},
      {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""}, {""},
      {""}, {""}, {""}, {""}, {""},
      {"void", TYPESPEC, RID_VOID}
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          register const char *s = wordlist[key].name;

          if (*str == *s && !strcmp (str + 1, s + 1))
            return &wordlist[key];
        }
    }
  return 0;
}
