#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test file locations with file names that contain spaces.

# Note: This test fails on Linux with musl libc versions that don't support
# the GB18030 encoding in 'iconv'.

cat <<\EOF > mcat-test22.po
msgid ""
msgstr ""
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ‚Å®xg-test17 a.c‚Å©:1 ‚Å®xg-test17 x y.c‚Å©:1
msgid "foo"
msgstr ""

#: ‚Å®xg-test17 x y.c‚Å©:2 xg-test17z.c:1
msgid "bar"
msgstr ""
EOF

: ${MSGCAT=msgcat}
${MSGCAT} --to-code=UTF-8 \
          -o mcat-test22.out1 mcat-test22.po || Exit 1

: ${DIFF=diff}
${DIFF} mcat-test22.po mcat-test22.out1 || Exit 1

: ${MSGCAT=msgcat}
${MSGCAT} --to-code=GB18030 \
          -o mcat-test22.2.po mcat-test22.po || Exit 1

cat <<\EOF > mcat-test22.ok
msgid ""
msgstr ""
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=GB18030\n"
"Content-Transfer-Encoding: 8bit\n"

#: Å6¨4xg-test17 a.cÅ6¨5:1 Å6¨4xg-test17 x y.cÅ6¨5:1
msgid "foo"
msgstr ""

#: Å6¨4xg-test17 x y.cÅ6¨5:2 xg-test17z.c:1
msgid "bar"
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} mcat-test22.ok mcat-test22.2.po || Exit 1

: ${MSGCAT=msgcat}
${MSGCAT} --to-code=GB18030 \
          -o mcat-test22.out2 mcat-test22.2.po || Exit 1

: ${DIFF=diff}
${DIFF} mcat-test22.2.po mcat-test22.out2 || Exit 1

: ${MSGCAT=msgcat}
${MSGCAT} --to-code=UTF-8 \
          -o mcat-test22.out3 mcat-test22.2.po || Exit 1

: ${DIFF=diff}
${DIFF} mcat-test22.po mcat-test22.out3 || Exit 1

: ${MSGCAT=msgcat}
${MSGCAT} --to-code=ISO-8859-1 \
          -o mcat-test22.out4 mcat-test22.po 2>/dev/null
test $? = 1 || Exit 1

exit 0
