#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test of Icon handling in Desktop Entry support.

cat <<\EOF > hello.desktop
[Desktop Entry]
Name=Hello
TryExec=hello
Exec=hello
Icon=handshake.jpg
Icon[en_US]=hifive.jpg
Icon[th]=wai.jpg
Type=Application
Keywords=Utility;
EOF

cat <<\EOF > th.po
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-18 12:45+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Thai <th@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: hello.desktop:3
msgid "Hello"
msgstr "สวัสดี"

#: hello.desktop:10
msgid "Utility;"
msgstr "ประโยชน์;"
EOF

cat <<\EOF > hello.desktop.ok
[Desktop Entry]
Name[th]=สวัสดี
Name=Hello
TryExec=hello
Exec=hello
Icon=handshake.jpg
Icon[en_US]=hifive.jpg
Icon[th]=wai.jpg
Type=Application
Keywords[th]=ประโยชน์;
Keywords=Utility;
EOF

# Generate the merged .desktop file.

${MSGFMT} --desktop --template=hello.desktop -l th th.po -o hello.desktop.tmp \
  || Exit 1
LC_ALL=C tr -d '\r' < hello.desktop.tmp > hello.desktop.out || Exit 1

: ${DIFF=diff}
${DIFF} hello.desktop.ok hello.desktop.out
result=$?

exit $result
