#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test empty msgstr handling.
# <https://savannah.gnu.org/bugs/?43720>

cat <<\EOF > mfi-test7.po
# HEADER.
#
msgid ""
msgstr ""
"Project-Id-Version: Bonnie Tyler\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: married-men:4
#, fuzzy
msgid "The world is full of married men"
msgstr "So viele verheiratete Männer"

#: married-men:5
msgid "with wives who never understand"
msgstr "und ihre Frauen verstehen sie nicht"

#: married-men:6
msgid "They're looking for someone to share"
msgstr ""

# schwer zu übersetzen...
#: married-men:7
msgid "the excitement of a love affair"
msgstr ""

#: married-men:8
msgid "Just as soon as they find you"
msgstr ""

#: married-men:9
msgid "They warn you and darn you"
msgstr ""

#~ msgid "You fly on the wings of romance"
#~ msgstr "Die Flügel der frischen Liebe heben dich zum Himmel"

#, fuzzy
#~ msgid "In the eyes of the world"
#~ msgstr "Für die anderen"

# Etwas freie Übersetzung.
#~ msgid "You're just another crazy girl"
#~ msgstr "bist du bloß ein verrücktes dummes Ding"

#~ msgid "Who loves a married man"
#~ msgstr "das einen verheirateten Mann liebt"
EOF

cat <<\EOF > mf-test7.sh
#! /bin/sh

# Eat up filter input to avoid EPIPE in the parent process.
cat > /dev/null

echo testing
EOF
chmod +x mf-test7.sh

: ${MSGFILTER=msgfilter}
LC_ALL=C ${MSGFILTER} -i mfi-test7.po -o mfi-test7.out \
      ./mf-test7.sh >mfi-test7.err 2>&1
result=$?
cat mfi-test7.err | grep -v 'warning: Locale charset' | grep -v '^ '
test $result = 0 || { Exit 1; }

cat <<\EOF > mfi-test7.ok
# HEADER.
#
msgid ""
msgstr "testing\n"

#: married-men:4
#, fuzzy
msgid "The world is full of married men"
msgstr "testing\n"

#: married-men:5
msgid "with wives who never understand"
msgstr "testing\n"

#: married-men:6
msgid "They're looking for someone to share"
msgstr "testing\n"

# schwer zu übersetzen...
#: married-men:7
msgid "the excitement of a love affair"
msgstr "testing\n"

#: married-men:8
msgid "Just as soon as they find you"
msgstr "testing\n"

#: married-men:9
msgid "They warn you and darn you"
msgstr "testing\n"

#~ msgid "You fly on the wings of romance"
#~ msgstr "testing\n"

#, fuzzy
#~ msgid "In the eyes of the world"
#~ msgstr "testing\n"

# Etwas freie Übersetzung.
#~ msgid "You're just another crazy girl"
#~ msgstr "testing\n"

#~ msgid "Who loves a married man"
#~ msgstr "testing\n"
EOF

: ${DIFF=diff}
${DIFF} mfi-test7.ok mfi-test7.out
result=$?

exit $result
