#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test msgfmt on a PO file with previous msgids.

cat <<\EOF > mf-16.po
msgid ""
msgstr ""
"Report-Msgid-Bugs-To: \n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#. TRANSLATORS: An error message.
#: src/args.c:242
#, fuzzy, c-format
#| msgid "too many arguments"
msgid "Too many arguments."
msgstr "zu viele Argumente"

#. TRANSLATORS: An error message.
#: src/args.c:247
#, fuzzy, c-format
#| msgid "too many arguments"
msgid "Too few arguments."
msgstr "zu viele Argumente"

# Oder besser "fehlende Argumente"?
#. TRANSLATORS: An error message.
#: src/args.c:273
#, c-format
#| msgid "missing arguments"
msgid "Missing arguments."
msgstr "Argumente fehlen."

#, fuzzy
#~| msgid "%s: invalid option -- %c\n"
#~ msgid "%s: illegal option -- %c\n"
#~ msgstr "%s: ungültige Option -- %c\n"

#~ msgid "%s: invalid option -- %c\n"
#~ msgstr "%s: ungültige Option -- %c\n"
EOF

: ${MSGFMT=msgfmt}
${MSGFMT} -o mf-16.mo mf-16.po || Exit 1

: ${MSGUNFMT=msgunfmt}
${MSGUNFMT} -o mf-16.tmp mf-16.mo || Exit 1
LC_ALL=C tr -d '\r' < mf-16.tmp > mf-16.out || Exit 1

cat <<\EOF > mf-16.ok
msgid ""
msgstr ""
"Report-Msgid-Bugs-To: \n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "Missing arguments."
msgstr "Argumente fehlen."
EOF

: ${DIFF=diff}
${DIFF} mf-16.ok mf-16.out
result=$?

exit $result
