#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test non-ASCII character at the end of msgstr. (Triggered a glibc-2.1 bug.)

cat <<\EOF > mm-test6.in1.po
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: cog_training 1.0\n"
"POT-Creation-Date: 2001-04-29 22:40+0200\n"
"PO-Revision-Date: 2001-04-29 21:19+02:00\n"
"Last-Translator: Felix Natter <fnatter@gmx.net>\n"
"Language-Team: German <de@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: cogarithmetic.cc:12 cogidmarkup.cc:288 cogroman.cc:14
msgid "white"
msgstr "weiﬂ"
EOF

cat <<EOF > mm-test6.in2.po
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2001-04-30 18:51+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: cogarithmetic.cc:12 cogidmarkup.cc:288 cogroman.cc:14
msgid "white"
msgstr ""

#: cogarithmetic.cc:13 cogroman.cc:109 cogroman.cc:114
msgid "false."
msgstr ""

#: cogarithmetic.cc:14
msgid "was correct."
msgstr ""
EOF

: ${MSGMERGE=msgmerge}
LC_MESSAGES=C LC_ALL= \
${MSGMERGE} -q -o mm-test6.tmp mm-test6.in1.po mm-test6.in2.po || Exit 1
LC_ALL=C tr -d '\r' < mm-test6.tmp > mm-test6.out || Exit 1

cat <<\EOF > mm-test6.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: cog_training 1.0\n"
"POT-Creation-Date: 2001-04-30 18:51+0200\n"
"PO-Revision-Date: 2001-04-29 21:19+02:00\n"
"Last-Translator: Felix Natter <fnatter@gmx.net>\n"
"Language-Team: German <de@li.org>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=ISO-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: cogarithmetic.cc:12 cogidmarkup.cc:288 cogroman.cc:14
msgid "white"
msgstr "weiﬂ"

#: cogarithmetic.cc:13 cogroman.cc:109 cogroman.cc:114
msgid "false."
msgstr ""

#: cogarithmetic.cc:14
msgid "was correct."
msgstr ""
EOF

: ${DIFF=diff}
${DIFF} mm-test6.ok mm-test6.out
result=$?

exit $result
