#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test of general operation.

cat <<EOF > mu-test1.in
msgid "eight"
msgstr "eighth"

msgid "five"
msgstr "fifth"

msgid "four"
msgstr "fourth"

msgid "one"
msgstr "first"

msgid "seven"
msgstr "seventh"

msgid "six"
msgstr "sixth"

msgid "three"
msgstr "third"

msgid "two"
msgstr "second"
EOF

: ${MSGFMT=msgfmt}
${MSGFMT} -o mu-test1.mo mu-test1.in || Exit 1

: ${MSGUNFMT=msgunfmt}
${MSGUNFMT} -o mu-test1.tmp mu-test1.mo || Exit 1
LC_ALL=C tr -d '\r' < mu-test1.tmp > mu-test1.out || Exit 1

: ${DIFF=diff}
${DIFF} mu-test1.in mu-test1.out
result=$?

exit $result
