#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test EmacsLisp support: stack overflow prevented by nesting depth check.

: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location -d xg-el-so-3.tmp "$wabs_srcdir"/testdata/xg-el-so-3.el 2>xg-el-so-3.err
result=$?
cat xg-el-so-3.err
test $result = 1 || Exit 1

exit 0
