#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test JavaScript support: XML Processing Instruction.

cat <<\EOF > xg-js-11a.js
<??>
EOF

cat <<\EOF > xg-js-11b.js
<?xml version="1.0" encoding="UTF-8"?>
EOF

: ${XGETTEXT=xgettext}
LANGUAGE= LC_ALL=C ${XGETTEXT} --no-location -d xg-js-11.tmp xg-js-11a.js 2>xg-js-11.err
result=$?
cat xg-js-11.err
test $result = 0 || Exit 1

: ${XGETTEXT=xgettext}
LANGUAGE= LC_ALL=C ${XGETTEXT} --no-location -d xg-js-11.tmp xg-js-11b.js 2>xg-js-11.err
result=$?
cat xg-js-11.err
test $result = 0 || Exit 1

exit 0
