#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test C support: extraction of 'range:' flags.

cat <<\EOF > xg-c-6.c
if (days > 7 && days < 14)
  /* xgettext: range: 1..6 */
  printf (ngettext ("one week and one day", "one week and %d days",
                    days - 7),
          days - 7);
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} --omit-header --no-location -d xg-c-6.tmp xg-c-6.c || Exit 1
LC_ALL=C tr -d '\r' < xg-c-6.tmp.po > xg-c-6.po || Exit 1

cat <<EOF > xg-c-6.ok
#, c-format, range: 1..6
msgid "one week and one day"
msgid_plural "one week and %d days"
msgstr[0] ""
msgstr[1] ""
EOF

: ${DIFF=diff}
${DIFF} xg-c-6.ok xg-c-6.po
result=$?

exit $result
