#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test JavaProperties extractor with escaped ASCII input.

cat <<\EOF > xg-pr-2.properties
dialog.open = \u00D6ffnen
dialog.close = Datei wurde ver\u00e4ndert. Trotzdem schlie\u00dfen?
EOF

: ${XGETTEXT=xgettext}
${XGETTEXT} -o xg-pr-2.tmp xg-pr-2.properties || Exit 1
func_filter_POT_Creation_Date xg-pr-2.tmp xg-pr-2.po

cat <<\EOF > xg-pr-2.ok
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "dialog.open"
msgstr "Öffnen"

msgid "dialog.close"
msgstr "Datei wurde verändert. Trotzdem schließen?"
EOF

: ${DIFF=diff}
${DIFF} xg-pr-2.ok xg-pr-2.po
result=$?

exit $result
