#!/bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test of Perl support: nesting depth check shouldn't prevent parsing a large
# but mostly flat input file.

: ${XGETTEXT=xgettext}
LANGUAGE= LC_ALL=C ${XGETTEXT} --no-location -d xg-pl-so-5.tmp "$wabs_srcdir"/testdata/xg-pl-so-5.pl 2>xg-pl-so-5.err
result=$?
cat xg-pl-so-5.err
test $result = 0 || Exit 1

exit 0
