#! /bin/sh
. "${srcdir=.}/init.sh"; path_prepend_ . ../src

# Test PO extractor with non-ASCII input file without header entry.

: ${XGETTEXT=xgettext}
${XGETTEXT} --no-location -d xg-po-4.tmp "$wabs_srcdir"/testdata/xg-po-4.po 2>xg-po-so-4.err
result=$?
cat xg-po-so-4.err
test $result = 1 || Exit 1

exit 0
