.\"gcloseall(1) man page
.\"put together by Dennis Leeuw <dleeuw@made-it.com>
.\"Copyright (C) 2003 Free Software Foundation, Inc.
.\"
.\"Process this file with
.\"groff -man -Tascii closeall.1
.\"
.TH GCLOSEALL 1 "December 2007" GNUstep "GNUstep System Manual"
.SH NAME
gcloseall \- This tool terminates all applications 
.SH SYNOPSIS
.B gcloseall
.P
.SH DESCRIPTION
.B gcloseall
terminates all applications. It does this by not asking any questions. It just terminates all applications. You have been warned!
.SH OPTIONS
.SH BUGS
None known

.P
.SH SEE ALSO
gclose(1), gopen(1), GNUstep(7)
.P
.SH HISTORY
Work on
.B gcloseall 
started in January 2006.
.P
.SH AUTHORS
gcloseall was written by Richard Frith-Macdoanld <rfm@gnu.org>
.P
This man page was written by Dennis Leeuw <dleeuw@made-it.com>.
