.\"gclose(1) man page
.\"put together by Dennis Leeuw <dleeuw@made-it.com>
.\"Copyright (C) 2003 Free Software Foundation, Inc.
.\"
.\"Process this file with
.\"groff -man -Tascii gclose.1
.\"
.TH GCLOSE 1 "December 2007" GNUstep "GNUstep System Manual"
.SH NAME
gclose \- This tool terminates an application
.SH SYNOPSIS
.B gclose <application>
.P
.SH DESCRIPTION
.B gclose
terminates an application from the command line
.SH OPTIONS
.SH BUGS
None known

.P
.SH SEE ALSO
gcloseall(1), gopen(1), GNUstep(7)
.P
.SH HISTORY
Work on
.B gclose
started in November 2001.
.P
.SH AUTHORS
gclose was written by Gregory Casamento <greg_casamento@yahoo.com>
.P
This man page was written by Dennis Leeuw <dleeuw@made-it.com>.
