include $(GNUSTEP_MAKEFILES)/common.make
BUNDLE_NAME=InvokeProxy
InvokeProxy_OBJC_FILES=InvokeProxy.m
InvokeProxy_NEEDS_GUI = NO
include $(GNUSTEP_MAKEFILES)/bundle.make
include $(GNUSTEP_MAKEFILES)/test-tool.make

check:: all
