.*: Assembler messages:
.*:5: Warning: macro instruction expanded into multiple instructions
.*:10: Warning: macro instruction expanded into multiple instructions
.*:11: Warning: macro instruction expanded into multiple instructions
.*:12: Warning: macro instruction expanded into multiple instructions
.*:16: Warning: macro instruction expanded into multiple instructions.*slot
.*:18: Warning: macro instruction expanded into multiple instructions.*slot
.*:20: Warning: macro instruction expanded into multiple instructions.*slot
