# Parenthesized `(...)' is the offset we cross-check.
# The third parenthesized value was left unrelocated (0x0) before.
#...
.*Abbrev Number: .* \(DW_TAG_variable\).*
#...
.*DW_AT_type *: *<0x(32)>.*
#...
.*<(32)>: Abbrev Number: .* \(DW_TAG_base_type\).*
#...
.*Compilation Unit.*
#...
.*Abbrev Number: .* \(DW_TAG_compile_unit\).*
#...
.*Abbrev Number: .* \(DW_TAG_variable\).*
#...
.*DW_AT_type        : <0x(32)>.*
#...
