#...
[0-9a-f]+ A abs_entry_fct
#...
[0-9a-f]+ T glob_entry_fct
#...
[0-9a-f]+ T glob_entry_veneer1
[0-9a-f]+ T glob_entry_veneer2
#...
[0-9a-f]+ W weak_entry_veneer1
[0-9a-f]+ W weak_entry_veneer2
#...
