#!/rescue/sh

if [ "`ps -o command 1 | tail -n 1 | ( read c o; echo ${o} )`" = "-s" ]; then
else
	if [ "`ps -o command 1 | tail -n 1 | ( read c o; echo ${o} )`" = "-v" ]; then
	else
		exec 1>>/dev/null 2>&1
	fi
fi

if [ ! -e /dev/md2 ] ; then
  halt -p
fi

echo "==> Ramdisk /etc/rc running"
echo "==> Unset rescue init kernel environment variables"
kenv -u init_chroot
kenv -u init_path
kenv -u init_script
kenv -u init_shell
echo "==> Unmount filesystems for cloning"
umount -f /livecd/dev
zpool export livecd
zpool export furybsd || true
umount -f /cdrom
echo "==> Set /dev/md2 device for reroot"
kenv vfs.root.mountfrom=zfs:livecd
echo "==> Rerooting into memdisk"
reboot -r
