#!perl
# for the use of t/porting/bench.pl.
#
# A file to load which has an invalid hash key


[ 
    'foo::bar' => {
        desc    => 'my $x = "abc"',
        setup   => '',
        code    => 'my $x = "abc"',
        blah    => 1,
    },
];

