#!perl
# for the use of t/porting/bench.pl.
#
# A file to load which has an invalid test name


[ 
    '1=' => {
        desc    => 'my $x = "abc"',
        setup   => '',
        code    => 'my $x = "abc"',
    },
];

